### ISSUE TITLE
Language is only in english in game

### ISSUE THREAD

**Issue by FredericVincent0** [MatteoPrampolini/CTDM#13]

**Comment by MatteoPrampolini** [comment]
This is intentional. The vast majority of custom tracks only have names in the English language. Furthermore, to the best of my knowledge, I have never encountered any custom track distribution that supports languages other than English. I believe there is currently no necessity for it. 
If there is a substantial demand for multi-language support from a significant number of users, then I may consider implementing it. At the moment, English is the sole language that CTDM will use for creating custom distributions.
