### ISSUE TITLE
BRSTM File Problems

### ISSUE THREAD

**Issue by ZeraoraKing** [MatteoPrampolini/CTDM#8]
- The program will cause an exception if you use a pre-made BRSTM for a track instead of a .wav file
- The program amplifies BRSTMs by a ton, causing distortion in-game
- There is no way to make loop points in BRSTMs, which makes songs end instead of looping at a defined point

**Comment by MatteoPrampolini** [comment]
> The program will cause an exception if you use a pre-made BRSTM for a track instead of a .wav file

My bad, I will fix it in the next release.

>The program amplifies BRSTMs by a ton, causing distortion in-game

Yes, the program amplifies the volume because in my tests (sample size=3) the volume in game was very low. This indeed may cause distortion. I might have to analyze the track volume before the amplification and then find out the right multiplier case by case. I think this is a low priority issue, but I may still sort it out in the next release.
>There is no way to make loop points in BRSTMs, which makes songs end instead of looping at a defined point

Good point. I should (hopefully) be able to fix it in the next release.

**Comment by MatteoPrampolini** [comment]
Everything should be fixed in [v0.8.1](https://github.com/MatteoPrampolini/CTDM/releases/tag/v0.8.1).
